# Traefik v3 Static Configuration
# OneWishOS Docker Stack

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: onewish-net
  file:
    directory: /etc/traefik/dynamic
    watch: true

ping: {}

log:
  level: INFO

accessLog: {}
