#!/bin/bash
# inject-secrets.sh — Populate .env from 1Password vault DevStack-Production
set -euo pipefail

VAULT="DevStack-Production"
ENV_FILE="$(dirname "$0")/../.env"

echo "🔑 Injecting secrets from 1Password vault: $VAULT"

# Verify op CLI is authenticated
if ! op whoami &>/dev/null; then
    echo "❌ 1Password CLI not authenticated. Run: eval $(op signin)"
    exit 1
fi

# Extract secrets
PG_PASS=$(op item get "Postgres-Local" --vault "$VAULT" --fields password --reveal 2>/dev/null || echo "")
REDIS_PASS=$(op item get "Qdrant-Local" --vault "$VAULT" --fields api_key --reveal 2>/dev/null || echo "")

cat > "$ENV_FILE" << EOF
# Auto-generated by inject-secrets.sh at $(date)
POSTGRES_PASSWORD=${PG_PASS}
REDIS_PASSWORD=${REDIS_PASS}
N8N_BASIC_AUTH_PASSWORD=$(openssl rand -base64 15)
N8N_ENCRYPTION_KEY=$(openssl rand -hex 16)
N8N_OWNER_PASSWORD_HASH=
INTELLIGENCEOS_N8N_PASSWORD=changeme
INTELLIGENCEOS_N8N_ENCRYPTION_KEY=$(openssl rand -hex 16)
NEO4J_AUTH=neo4j/changeme
INTELLIGENCEOS_NEO4J_AUTH=neo4j/changeme
GITHUB_PAT=PLACEHOLDER_ADD_GITHUB_PAT
EOF

chmod 600 "$ENV_FILE"
echo "✅ .env written to $ENV_FILE"
