#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────
# OneWishOS Docker Stack — Secret Injection
# Pulls credentials from 1Password → writes .env
# ─────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"
VAULT="DevStack-Production"

echo "🔑 Injecting secrets from 1Password vault: $VAULT"

# Check op CLI
if ! command -v op &>/dev/null; then
    echo "❌ 1Password CLI (op) not found. Install: brew install --cask 1password-cli"
    exit 1
fi

# Check authentication
if ! op account list &>/dev/null; then
    echo "❌ Not signed in to 1Password. Run: eval \$(op signin)"
    exit 1
fi

# Pull secrets
POSTGRES_USER=$(op item get "Postgres-Local" --vault "$VAULT" --fields username --reveal)
POSTGRES_PASSWORD=$(op item get "Postgres-Local" --vault "$VAULT" --fields password --reveal)
POSTGRES_DB=$(op item get "Postgres-Local" --vault "$VAULT" --fields database --reveal)
REDIS_PASSWORD=$(openssl rand -hex 16)  # Generate fresh Redis password
QDRANT_API_KEY=$(op item get "Qdrant-Local" --vault "$VAULT" --fields api_key --reveal)
TRAEFIK_USER=$(op item get "Traefik-Local" --vault "$VAULT" --fields username --reveal)
TRAEFIK_PASS=$(op item get "Traefik-Local" --vault "$VAULT" --fields password --reveal)

# Write .env
cat > "$ENV_FILE" <<EOF
# Auto-generated by inject-secrets.sh — DO NOT COMMIT
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Postgres
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB

# Redis
REDIS_PASSWORD=$REDIS_PASSWORD

# Qdrant
QDRANT_API_KEY=$QDRANT_API_KEY

# Traefik
TRAEFIK_DASHBOARD_USER=$TRAEFIK_USER
TRAEFIK_DASHBOARD_PASSWORD=$TRAEFIK_PASS
EOF

chmod 600 "$ENV_FILE"
echo "✅ Secrets written to $ENV_FILE"
